services:
  - type: web
    name: ai-linebot
    runtime: python
    plan: starter
    autoDeploy: true
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python scripts/setup_rich_menu.py
    startCommand: |
      gunicorn "app:create_app()" \
        --bind 0.0.0.0:$PORT \
        --workers 2 \
        --timeout 60 \
        --keep-alive 5 \
        --max-requests 2000 \
        --max-requests-jitter 200
    envVars:
      - key: RENDER_CACHE
        value: clear
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONDONTWRITEBYTECODE
        value: 1
      # 建議於 Render 控制台設定下列敏感資訊：
      # - LINE_CHANNEL_SECRET
      # - LINE_CHANNEL_ACCESS_TOKEN
      # - GCP_SERVICE_ACCOUNT_JSON
      # - CLOUDINARY_CLOUD_NAME
      # - CLOUDINARY_API_KEY
      # - CLOUDINARY_API_SECRET
      # - REDIS_URL
    scaling:
      minInstances: 1
      maxInstances: 3
      targetCPUPercent: 90

  # Redis 服務（可選，若不使用外部 Redis）
  - type: redis
    ipAllowList: []  # 允許所有 IP 存取，或填入特定 IP
    name: ai-linebot-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru
